pipeline {
  agent {
    kubernetes {
        label 'jenkins-slave'
        defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: dind
    image: docker:18.09-dind
    securityContext:
      privileged: true
  - name: docker
    env:
    - name: DOCKER_HOST
      value: 127.0.0.1
    image: docker:18.09
    command:
    - cat
    tty: true
  - name: tools
    env:
    - name: DOCKER_HOST
      value: 127.0.0.1
    image: ahmedulde/argo-cd-ci-builder
    command:
    - cat
    tty: true
  imagePullSecrets:
  - name: regcred    
"""
    }
  }
  stages {

    stage('FrontEnd') {
      environment {
        GIT_CREDS = credentials('GithubLogin')
      }
      steps {
        container('dind') {
          // Build new image  
          sh "apk update && apk add git"
          sh "git clone https://github.com/ahmedulde7/guestbook.git"
          sh "pwd"
          sh "docker login -u ahmedulde -p Cooldude@007"
          sh "until docker ps; do sleep 3; done && cd guestbook/frontend && docker build -t ahmedulde/guestbook-frontend-demo:${env.GIT_COMMIT} ."
          // Publish new image
          sh "docker push ahmedulde/guestbook-frontend-demo:${env.GIT_COMMIT}"
        }
      }
    }

    stage('Trigger ArgoCD') {
      environment {
        GIT_CREDS = credentials('GithubLogin')
      }
      steps{
        container('tools') {
          sh "echo $GIT_CREDS"
          sh "echo ${env.GIT_COMMIT}"
          sh "kustomize version"
          sh "git config --global user.email \"ahmedulde7@gmail.com\"" 
          sh "git config --global user.name \"ahmedulde7\"" 
          sh "cd dev && kustomize edit set image ahmedulde/guestbook-frontend-demo:${env.GIT_COMMIT}"
          sh "git commit -am 'Publish new version' && git push origin HEAD:master|| echo 'no changes'"
        }
      }
    }
  }
}
