apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: java-guestbook-frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: ENVIRONMENT
          value: dev