apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./guestbook-frontend.deployment-patch.yaml

resources:
- ../../

images:
- name: ahmedulde/guestbook-frontend-demo
  newTag: 453d6c40b7722951c1f009754959cff86adc9e67
