apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - ./guestbook-frontend.deployment-patch.yaml

resources:
  - ../../base

images:
- name: ahmedulde/guestbook-frontend-demo
  newTag: testing


